# Training performed with CTLearn version 0.3.0.
Data:
  event_info:
  - particle_id
  file_list: /home/shevek/datasets/prototype/prototype_files_class_balanced.txt
  image_channels:
  - image_charge
  mapping_settings:
    padding:
      ASTRICam: 0
      CHEC: 0
      DigiCam: 1
      FlashCam: 1
      LSTCam: 2
      NectarCam: 2
      SCTCam: 4
      VERITAS: 1
  mode: mono
  seed: 1111
  selected_telescope_type: SST1
  shuffle: true
  transforms:
  - name: ConvertShowerPrimaryIDToClassLabel
Input:
  batch_size: 64
  prefetch_buffer_size: 2
  seed: 1234
  shuffle_buffer_size: 10000
Logging:
  model_directory: /data0/logs/icrc2019/190625_legacy_benchmark/run00
Model:
  label_names:
    class_label:
    - proton
    - gamma
  model:
    function: single_tel_model
    module: single_tel
  model_directory: null
Model Parameters:
  basic:
    conv_block:
      batchnorm: false
      bottleneck: null
      layers:
      - filters: 32
        kernel_size: 3
      - filters: 32
        kernel_size: 3
      - filters: 64
        kernel_size: 3
      - filters: 128
        kernel_size: 3
      max_pool:
        size: 2
        strides: 2
  single_tel:
    network:
      function: conv_block
      module: basic
    pretrained_weights: null
Prediction:
  export_as_file: true
  prediction_file_path: /tmp/mypredictions.csv
  save_identifiers: true
  save_labels: true
TensorFlow:
  run_TFDBG: false
Training:
  adam_epsilon: 1.0e-08
  apply_class_weights: false
  base_learning_rate: 5.0e-05
  num_training_steps_per_validation: 2500
  num_validations: 20
  optimizer: Adam
  scale_learning_rate: false
  validation_split: 0.1
  variables_to_train: null
