# conda env create -f environment.yml
name: ctlearn
channels:
    - conda-forge
channel_priority: strict
dependencies:
    - python=3.10
    - astropy
    - setuptools
    - numpy
    - pandas
    - pip
    - pytables
    - tables
    - c-blosc2=2.13
    - pyyaml
    - scikit-learn
    - ctapipe
    - numba
    - tensorflow=2.14
    - pydot
    - pip:
        - dl1_data_handler>=0.14.5,<0.15

