# conda env create -f environment.yml
name: ctlearn
channels:
    - anaconda
    - conda-forge
dependencies:
    - python=3.12
    - astropy
    - setuptools
    - numpy
    - pandas
    - pip
    - pytables
    - tables
    - c-blosc2=2.13
    - pyyaml
    - scikit-learn
    - ctapipe
    - pip:
        - numba
        - tensorflow>=2.19,<2.21
        - dl1_data_handler>=0.14.5,<0.15
        - pydot
