# conda env create -f environment-cluster.yml
name: ctlearn-cluster
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - ctlearn-project
dependencies:
    - python=3.10
    - astropy
    - numpy
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        - ctaplot
        - dl1_data_handler==0.12.0
        - matplotlib==3.6.2
        - iminuit==2.24.0
        - numba>=0.56.2,<0.57
        - numexpr==2.8.4
        - kiwisolver==1.4
        - tensorflow>=2.14,<2.15
        - pydot
        - pyirf
        - pandas==1.5.2
        - pillow==9.3.0
        - scipy==1.11.1
        - tables==3.8.0

