# conda env create -f environment.yml
name: ctlearn
channels:
    - anaconda
    - conda-forge
    - cta-observatory
    - ctlearn-project
dependencies:
    - python=3.10
    - astropy
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - pip:
        - ctaplot
        - numba>=0.56.2,<0.57
        - tensorflow>=2.15,<2.16
        - dl1_data_handler==0.12.0
        - pydot
        - pyirf
